### ISSUE TITLE
Find a nice way to output a summary of the model object

### ISSUE THREAD

**Issue by DrMattG** [DrMattG/InterEco#2]
Using jtools::summ() gives a summary of the object but it renders in an ugly way - maybe we need a function to tidy the output in to html and then render it?

**Comment by Becks-Spake** [comment]
Think we might just need to extract the important parts of the output and shove them into a data frame?
e.g., 
coefdat <- jtools::summ(bestmod)
coefdat <- round(data.frame(dat$coeftable),3)
renderTable(output$coefdat)
?

**Comment by DrMattG** [comment]
Like this? https://github.com/DrMattG/InterEco/pull/4
